// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUoGGAhxt0N6mqmD5seD4PLWCcBWkj8cY',
    appId: '1:917039863920:web:99073c63ee1e3a4f223cb5',
    messagingSenderId: '917039863920',
    projectId: 'study-informatika-6d21b',
    authDomain: 'study-informatika-6d21b.firebaseapp.com',
    storageBucket: 'study-informatika-6d21b.appspot.com',
    measurementId: 'G-XYKHRQ6RB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOdAfo26phtRBhpUD10L5PrqCVELItbX4',
    appId: '1:917039863920:android:754b7b463a8bffce223cb5',
    messagingSenderId: '917039863920',
    projectId: 'study-informatika-6d21b',
    storageBucket: 'study-informatika-6d21b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiF4BrhjrV36UEtUZZz4HJpsNY4hgfg2Y',
    appId: '1:917039863920:ios:79def8164f4d9c41223cb5',
    messagingSenderId: '917039863920',
    projectId: 'study-informatika-6d21b',
    storageBucket: 'study-informatika-6d21b.appspot.com',
    iosClientId: '917039863920-cvss9ps6dmlab89okj3kd5b3lpb8oa0d.apps.googleusercontent.com',
    iosBundleId: 'com.naufalcorp.studyInformatika',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiF4BrhjrV36UEtUZZz4HJpsNY4hgfg2Y',
    appId: '1:917039863920:ios:fd76b2de1a33c489223cb5',
    messagingSenderId: '917039863920',
    projectId: 'study-informatika-6d21b',
    storageBucket: 'study-informatika-6d21b.appspot.com',
    iosClientId: '917039863920-tent2lk92q00r252gn4vh1lbrik065li.apps.googleusercontent.com',
    iosBundleId: 'com.naufalcorp.studyInformatika.RunnerTests',
  );
}
